travis:
  secure:
    BINSTAR_TOKEN: bpHZS8xaTTDxDBTr3XpJZTgBhFpdKLS1Wu1H2DBOKeKsZKKPVzsa1j+uok++Oe0/MHRDmZusJndOAKanL5BnkLxQXB+zmBw5rM+J8lSuvr1W0S1p7Yn6Pm1WABXyhu56fO8AE2h0gWWvjsrzeTwfUr1FpCjZ7o0SAiuV2wuK0HD/fBxVDR6CdqZrqAskTcqrDjdeNLkYd7AW9+YIiEaRFZAQ4nshvv6+dHgQFMJdtqhOSu/1yAMMCtTRTXT7znPZwCMXvYmjpWlSer2XoGEUFijYX84ky17/EpmLJmY2QNL5ILG5npykqrb0v+Mi4ry3bBuTh80GB9fNuFDYYjLVoxxd9pFn+Q/dbRmsw3Yb28mR4u9y6btFAMzyiQADa0STnWUNHczsqIHgkBwUaIEBQUmPbNfVXseuu1PbQ4E/XNE+r6ISCwjLYBzHRlxDx7TgfTIAu3ddkFYr6gUReSETj1C2oTkv7SFxvABNc9oJzON2LsjT3Ce/euzCcfilhJjO+J0yZH56/kIOzUxDSmqRWHHekMfya/R39rw5ji2nxXOwx6m275PbWbSvueHLqtx45/SsGblv2uj6/JTa0yOcf0XxhJCLSfmpLbM5yfkNj78qfPcVfm1V7za8qAjQemw1O8uqLaQAhQalFLmgsHQilkLL0KMZMjxRfT9404ab+3I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
